### ISSUE TITLE
Chris Done projects: Duet, Inflex

### ISSUE THREAD

**Issue by yairchu** [yairchu/awesome-structure-editors#17]
Hi @chrisdone (or anyone else familiar with Duet or Inflex) -

I'm compiling a list of structural and projectional code editor projects and would like to include your projects here. Could you take a look on this list and add the info on your projects? Thanks 🙏

**Comment by chrisdone** [comment]
I'm not sure how you format and choose what to put in your README, but here's some details:

* [Duet epsilon](https://chrisdone.com/toys/duet-epsilon/) - a structural/projectional editor similar to Lamdu for the [Duet](https://github.com/chrisdone/duet) language. You can type e.g. `case` `SPC` or `+` or `\` and it inserts those AST nodes and type checks as you go, and backspace deletes nodes. I don't remember why I stopped working on this, probably lost interest.
* [Novella](https://github.com/chrisdone/novella) - I started working on which was another structured editor with which I intended to make it very easy to write a structured editor for any language I was interested in (like Haskell or SQL). [Example for Haskell](https://github.com/chrisdone/novella/blob/master/src/Novella/Languages/Haskell.hs). I gave up on that as Inflex took up all my attention.
* [Inflex](https://inflex.io/) is a commercial closed source (for now) app, with its own pure typed strict language with row types for records/variants. That's a little different, because you write plain text code in individual cells, but then the results of evaluating the cells can be edited "in-place" e.g. [1,2,3] can be edited like a table, and the edits are reflected back into the source code. The idea being that sometimes either text or structure are more intuitive to edit depending on the task. I haven't yet added, but will eventually add editing of lambdas and therefore any part of the AST, but in a limited way. It also doesn't store an AST in the database, it stores source code, but it is CAS. One can't refer to globals by name, either one refers to other cells by UUID @uuid:dsdf-sdfsdf-sdfsdf-sdfsdf.. (which are displayed by the editor as the display name), or to other documents by SHA512 @sha512:sdfslfkjsdf.., or primitives by @prim:foo (also pretty printed by the editor). I have some slides [here](https://docs.google.com/presentation/d/10aw_x3NbJSwDA9rIBhTa1CfdJS-aKwu7UyDIE4g8vQU/edit#slide=id.gc28f59af57_0_162).
